inherit_from: rubocop-todo.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - vendor/**/*
    - db/schema.rb
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

LineLength:
  Max: 80
  Exclude:
    - db/seeds/**
    - config/initializers/secret_token.rb

MethodLength:
  Max: 15

Documentation:
  Enabled: true
  Exclude:
    - app/helpers/**
    - app/models/**
    - app/controllers/**
    - db/migrate/**

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - '**/*_spec.rb'

Blocks:
  Enabled: false

LineEndConcatenation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '||'
    '%i': '||'
    '%q': '||'
    '%Q': '||'
    '%r': '{}'
    '%s': '||'
    '%w': '||'
    '%W': '||'
    '%x': '||'
