inherit_from: rubocop-todo.yml

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - tmp/**
    - bin/**
  RunRailsCops: true

LineLength:
  Max: 80
  Exclude:
    - db/seeds/**
    - config/initializers/secret_token.rb

MethodLength:
  Max: 15

Documentation:
  Enabled: true
  Exclude:
    - app/helpers/**
    - app/models/**
    - app/controllers/**
    - db/migrate/**

StringLiterals:
  Enabled: true
  Exclude:
    - spec/**

Blocks:
  Enabled: false

LineEndConcatenation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '||'
    '%i': '||'
    '%q': '||'
    '%Q': '||'
    '%r': '{}'
    '%s': '||'
    '%w': '||'
    '%W': '||'
    '%x': '||'
