inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
    - db/schema.rb
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 90
  Exclude:
    - db/seeds/**
    - config/initializers/secret_token.rb

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - '**/*_spec.rb'

Style/LineEndConcatenation:
  Enabled: false

# TODO: enable this when Ruby 3.0 is out.
Style/FrozenStringLiteralComment:
  Enabled: false
