inherit_from: rubocop-todo.yml

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - tmp/**
  RunRailsCops: true

LineLength:
  Max: 80
  Exclude:
    - db/seeds/**
    - config/initializers/secret_token.rb
