common: &common
  adapter: postgresql
  encoding: unicode
  reconnect: true
  host: localhost
  username: postgres
  password: postgres
test:
  <<: *common
  database: kyrylo_test
development:
  <<: *common
  database: kyrylo_development
staging:
  <<: *common
  database: kyrylo_staging
production:
  <<: *common
  database: kyrylo_production
